config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id          :bigint           not null, primary key
#  name        :string(255)
#  bio         :text(65535)
#  gender      :string(255)
#  total_books :integer
#  summary     :text(65535)
#  born        :date
#  died        :date
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Author < ApplicationRecord
  include FormattedAttr
  has_many :book_authors, dependent: :destroy
  has_many :books, through: :book_authors
  has_formatted_date :born, :died
  has_shorten_text :bio, :summary
  has_rich_text :bio
  has_rich_text :summary

  enum :gender, [ :male, :female ]
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @pagy, @authors = pagy(Author.order(created_at: :desc), items: 10)
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :bio, :gender, :total_books, :summary, :born, :died)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.slim
tr
  td.border-b.border-slate-100.underline.dark:border-slate-700.p-4.pl-8.text-slate-800.dark:text-slate-400
    = link_to author_path(author)
      = author.name
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    == author.shorten_bio
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = author.gender.humanize
  td.border-b.border-slate-100.underline.dark:border-slate-700.p-4.pl-8.text-slate-800.dark:text-slate-400
    = link_to books_path(author_ids: author.id)
      = author.total_books.to_i
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    == author.shorten_summary
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = author.formatted_born
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = author.formatted_died
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = link_to edit_author_path(author) do
      svg.inline-block.w-4.h-4[fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
        path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"]
    = button_to author_path(author), method: :delete, form_class: "inline-block ml-4",form: { data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } }  do
      svg.inline-block.w-4.h-4[fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
        path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"]

app/views/authors/_form.html.slim
= form_with(model: author, class: "contents") do |form|
  - if author.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      h2
        = pluralize(author.errors.count, "error")
        |  prohibited this author from being saved:
      ul
        - author.errors.each do |error|
          li
            = error.full_message
  .my-5
    = form.label :name
    = form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :bio
    = form.rich_text_area :bio, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :gender
    = form.select :gender, {'Male': 'male', 'Female': 'female'},
                              {},
                              class: 'w-full',
                              data: { controller: 'tom-select'}
  .my-5
    = form.label :summary
    = form.rich_text_area :summary, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :born
    = form.date_field :born, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :died
    = form.date_field :died, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/authors/edit.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | Editing author
  = render "form", author: @author
  = link_to "Show this author", @author, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to authors", authors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/authors/index.html.slim
w-full
  .mx-auto.md:w-2/3.w-full.flex
    .mx-auto
      - if notice.present?
        p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
          = notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl
      | Authors
    = link_to 'New Author', new_author_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"

  table.border-collapse.table-fixed.w-full.text-sm.my-5
    thead
      tr
        th.border-b.dark:border-slate-600.font-medium.p-4.pl-8.pt-0.pb-3.text-left
          | Name
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Bio
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Gender
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Total Books
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Summary
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Born
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Died
        th.border-b.dark:border-slate-600.font-medium.p-4.pr-8.pt-0.pb-3.text-left
          | Action
    tbody.bg-white.dark:bg-slate-800
      = render @authors
  .flex.justify-center.mb-5
    - if @pagy.present?
      == pagy_nav(@pagy, link_extra: 'data-turbo-action="advance"')

app/views/authors/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | New Author
  = render "form", author: @author
  = link_to 'Back to authors', authors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/authors/show.html.slim
.mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
.md:grid.md:grid-cols-3.md:gap-6
  .mt-5.md:col-span-3.md:mt-0
    h3.font-bold.text-2xl.pb-3
      | Author Detail
    .shadow.sm:overflow-hidden.sm:rounded-md
      .space-y-6.bg-white.px-4.py-5.sm:p-6
         div
          label.block.text-sm.font-medium.text-gray-700
            | Name
          p.mt-2.text-sm.text-gray-500
            = @author.name
         div
          label.block.text-sm.font-medium.text-gray-700
            | Bio
          p.mt-2.text-sm.text-gray-500
            == @author.bio
         div
          label.block.text-sm.font-medium.text-gray-700
            | Gender
          p.mt-2.text-sm.text-gray-500
            = @author.gender
         div
          label.block.text-sm.font-medium.text-gray-700
            | Total Books
          p.mt-2.text-sm.text-gray-500
            = @author.total_books.to_i
         div
          label.block.text-sm.font-medium.text-gray-700
            | Summary
          p.mt-2.text-sm.text-gray-500
            == @author.summary
         div
          label.block.text-sm.font-medium.text-gray-700
            | Born
          p.mt-2.text-sm.text-gray-500
            = @author.born
         div
          label.block.text-sm.font-medium.text-gray-700
            | Died
          p.mt-2.text-sm.text-gray-500
            = @author.died
         .bg-gray-50.px-4.py-3.text-right.sm:px-6
            = link_to 'Edit this author', edit_author_path(@author), class: "mt-2 rounded-lg py-3 px-5 bg-blue-500 text-white inline-block font-medium"
            .inline-block.ml-2
              = button_to 'Destroy this author', author_path(@author), method: :delete,form: { data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } }, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 text-white font-medium"
            = link_to 'Back to authors', authors_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"