config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :authors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "books#index"
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                :bigint           not null, primary key
#  author_id         :bigint           not null
#  content_name      :string(255)
#  isbn              :string(255)
#  original_title    :string(255)
#  year              :string(255)
#  language_code     :string(255)
#  category          :string(255)
#  plot              :text(65535)
#  copyright         :string(255)
#  title             :string(255)
#  average_rating    :float(24)
#  rating_count      :integer
#  description       :text(65535)
#  loc_class         :string(255)
#  language          :string(255)
#  pages             :integer
#  isbn13            :string(255)
#  release_date      :date
#  cover             :string(255)
#  summary           :text(65535)
#  content_cleaned   :boolean
#  content_available :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Book < ApplicationRecord
  include FormattedAttr
  mount_uploader :cover, CoverUploader

  has_many :book_authors, dependent: :destroy
  has_many :authors, through: :book_authors
  has_formatted_date :release_date
  has_shorten_text :plot, :description, :summary
  has_rich_text :plot
  has_rich_text :description
  has_rich_text :summary

  validates :authors, presence: true

  scope :filter_by_authors, -> (author_ids) { joins(:authors).where(authors: { id: author_ids }) }
  scope :filter_by_years, -> (years) { where(year: years) }
  scope :filter_by_pages, -> (pages) { where(pages: pages[0]..pages[1]) }
  scope :filter_by_keyword, -> (keyword) { where('LOWER(title) LIKE ? OR LOWER(original_title) LIKE ? ', "%#{keyword}%", "%#{keyword}%") }

  def self.humanize_options_page
    [
      '< 100',
      '100-250',
      '250-500',
      '500-750',
      '750-1000',
      '> 1000',
    ]
  end

  def self.options_page(humanize_option)
    return unless humanize_option.present?

    range = humanize_option.split('-')
    return range.map(&:to_i) if range.count > 1

    if humanize_option.match('<')
      [0, humanize_option.delete("^0-9").to_i]
    elsif humanize_option.match('>')
      [humanize_option.delete("^0-9").to_i, 9999999999]
    else
      []
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :set_authors
  # GET /books or /books.json
  def index
    pages    = Book.options_page(params[:pages])
    filtered = Book.includes(:authors)

    filtered = filtered.filter_by_authors(params[:author_ids]) if params[:author_ids].present?
    filtered = filtered.filter_by_years(params[:years]) if params[:years].present?
    filtered = filtered.filter_by_pages(pages) if pages.present?
    filtered = filtered.filter_by_keyword(params[:keyword]) if params[:keyword].present?
    @pagy, @books = pagy(filtered.order(created_at: :desc), items: 10)
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.replace(@book, 'show')
        # end
        format.html { redirect_to book_url(@book), status: :see_other, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:content_name, :isbn, :original_title, :year, :language_code, :category, :plot, :copyright, :title, :average_rating, :rating_count, :description, :loc_class, :language, :pages, :isbn13, :release_date, :cover, :summary, :content_cleaned, :content_available, author_ids: [])
    end

    def set_authors
      @authors = Author.all
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.slim
tr
  td.border-b.border-slate-100.underline.dark:border-slate-700.p-4.pl-8.text-slate-800.dark:text-slate-400
    = link_to book_path(book)
      = book.title
  td.border-b.border-slate-100.underline.dark:border-slate-700.p-4.pl-8.text-slate-800.dark:text-slate-400
    ul.list-disc
      - book.authors.each do |author|
        li
          = link_to author_path(author)
            = author.name
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = book.year
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = book.average_rating.to_f.round(1)
    = " - (#{book.rating_count.to_i})"
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = book.pages
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = book.release_date
  td.border-b.border-slate-100.dark:border-slate-700.p-4.pl-8.text-slate-500.dark:text-slate-400
    = link_to edit_book_path(book) do
      svg.inline-block.w-4.h-4[fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
        path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"]
    = button_to book_path(book), method: :delete,form: { data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } }, form_class: "inline-block ml-4" do
      svg.inline-block.w-4.h-4[fill="none" stroke="currentColor" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"]
        path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"]

app/views/books/_filter.html.slim
.mt-5.md:col-span-2.md:mt-0
  = form_with url: books_path, method: :get do
    .sm:rounded-md
      .bg-white.px-4.py-5.sm:p-6
        .grid.grid-cols-6.gap-6
          .col-span-6.sm:col-span-3
            label.block.text-sm.font-medium.text-gray-700
              | Keyword
            = text_field_tag "keyword", nil, placeholder: "Keyword", class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-100 focus:ring-indigo-100 sm:text-sm", value: params[:keyword]
          .col-span-6.sm:col-span-3
            label.block.text-sm.font-medium.text-gray-700
              | Authors
            = select_tag "author_ids", options_from_collection_for_select(@authors, 'id', 'name', params[:author_ids]),
                                       include_blank: true,
                                       class: 'w-full',
                                       data: { controller: 'tom-select' },
                                       multiple: true
          .col-span-6.sm:col-span-3
            label.block.text-sm.font-medium.text-gray-700
              | Years
            = select_tag "years", options_for_select((1200...Date.today.year).to_a, params[:years]),
                                  include_blank: true,
                                  class: 'w-full',
                                  data: { controller: 'tom-select' },
                                  multiple: true
          .col-span-6.sm:col-span-3
            label.block.text-sm.font-medium.text-gray-700
              | Pages
            = select_tag "pages", options_for_select(Book.humanize_options_page, params[:pages]),
                                  include_blank: true,
                                  class: 'w-full',
                                  data: { controller: 'tom-select' }
      .bg-gray-50.px-4.py-3.sm:px-6
        button.inline-flex.justify-center.rounded-md.border.border-transparent.bg-indigo-600.py-2.px-4.text-sm.font-medium.text-white.shadow-sm.hover:bg-indigo-700.focus:outline-none.focus:ring-2.focus:ring-indigo-500.focus:ring-offset-2[type="submit"]
          | Filter

app/views/books/_form.html.slim
= form_with(model: book, class: "contents") do |form|
  - if book.errors.any?
    #error_explanation.bg-red-50.text-red-500.px-3.py-2.font-medium.rounded-lg.mt-3
      h2
        = pluralize(book.errors.count, "error")
        |  prohibited this book from being saved:
      ul
        - book.errors.each do |error|
          li
            = error.full_message
  .my-5
    = form.label :authors
    = form.collection_select :author_ids, @authors, :id, :name,
                              {},
                              class: 'w-full',
                              data: { controller: 'tom-select'},
                              multiple: true
  .my-5
    = form.label :content_name
    = form.text_field :content_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :isbn
    = form.text_field :isbn, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :original_title
    = form.text_field :original_title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :year
    = form.text_field :year, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :language_code
    = form.text_field :language_code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :category
    = form.text_field :category, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :plot
    = form.rich_text_area :plot, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :copyright
    = form.text_field :copyright, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :title
    = form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :average_rating
    = form.text_field :average_rating, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :rating_count
    = form.number_field :rating_count, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :description
    = form.rich_text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :loc_class
    = form.text_field :loc_class, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :language
    = form.text_field :language, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :pages
    = form.number_field :pages, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :isbn13
    = form.text_field :isbn13, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :release_date
    = form.date_field :release_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :cover
    = form.file_field :cover, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :summary
    = form.rich_text_area :summary, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"
  .my-5
    = form.label :content_cleaned
    = form.check_box :content_cleaned, class: "block mt-2 h-5 w-5"
  .my-5
    = form.label :content_available
    = form.check_box :content_available, class: "block mt-2 h-5 w-5"
  .inline
    = form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer"

app/views/books/edit.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | Editing book
  = render "form", book: @book
  = link_to "Show this book", @book, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
  = link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/books/index.html.slim
.w-full
  .mx-auto.md:w-2/3.w-full.flex
    .mx-auto
      - if notice.present?
        p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
          = notice
  .flex.justify-between.items-center
    h1.font-bold.text-4xl
      | Books
    = link_to 'New book', new_book_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium"
  div
    = render 'filter'
  table.border-collapse.table-fixed.w-full.text-sm.my-5
    thead
      tr
        th.border-b.dark:border-slate-600.font-medium.p-4.pl-8.pt-0.pb-3.text-left
          | Title
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Author
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Year
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Avg Rating (Total Rating)
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Total Pages
        th.border-b.dark:border-slate-600.font-medium.p-4.pt-0.pb-3.text-left
          | Release Date
        th.border-b.dark:border-slate-600.font-medium.p-4.pr-8.pt-0.pb-3.text-left
          | Action
    tbody.bg-white.dark:bg-slate-800
      = render @books
  .flex.justify-center.mb-5
    - if @pagy.present?
      == pagy_nav(@pagy)

app/views/books/new.html.slim
.mx-auto.md:w-2/3.w-full
  h1.font-bold.text-4xl
    | New book
  = render "form", book: @book
  = link_to 'Back to books', books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"

app/views/books/show.html.slim
.mx-auto.md:w-2/3.w-full.flex
  .mx-auto
    - if notice.present?
      p#notice.py-2.px-3.bg-green-50.mb-5.text-green-500.font-medium.rounded-lg.inline-block
        = notice
.md:grid.md:grid-cols-3.md:gap-6
  .mt-5.md:col-span-3.md:mt-0
    h3.font-bold.text-2xl.pb-3
      | Book Detail
    .shadow.sm:overflow-hidden.sm:rounded-md
      .space-y-6.bg-white.px-4.py-5.sm:p-6
        div
          label.block.text-sm.font-medium.text-gray-700
            | Title
          p.mt-2.text-sm.text-gray-500
            = @book.title
        div
          label.block.text-sm.font-medium.text-gray-700
            | Cover
          .mt-1.flex.items-center
            span.inline-block.h-12.w-12.overflow-hidden.bg-gray-100
              = image_tag @book.cover_url
        div
          label.block.text-sm.font-medium.text-gray-700
            | Original Title
          p.mt-2.text-sm.text-gray-500
            = @book.original_title
        div
          label.block.text-sm.font-medium.text-gray-700
            | Author
          p.mt-2.text-sm.text-gray-500
            ul.list-disc
            - @book.authors.each do |author|
              li
                = link_to author_path(author)
                  = author.name
        div
          label.block.text-sm.font-medium.text-gray-700
            | Content Name
          p.mt-2.text-sm.text-gray-500
            = @book.content_name
        div
          label.block.text-sm.font-medium.text-gray-700
            | Isbn
          p.mt-2.text-sm.text-gray-500
            = @book.isbn

        div
          label.block.text-sm.font-medium.text-gray-700
            | Year
          p.mt-2.text-sm.text-gray-500
            = @book.year
        div
          label.block.text-sm.font-medium.text-gray-700
            | Language Code
          p.mt-2.text-sm.text-gray-500
            = @book.language_code
        div
          label.block.text-sm.font-medium.text-gray-700
            | Category
          p.mt-2.text-sm.text-gray-500
            = @book.category
        div
          label.block.text-sm.font-medium.text-gray-700
            | Plot
          p.mt-2.text-sm.text-gray-500
            == @book.plot
        div
          label.block.text-sm.font-medium.text-gray-700
            | Copyright
          p.mt-2.text-sm.text-gray-500
            = @book.copyright
        div
          label.block.text-sm.font-medium.text-gray-700
            | Title
          p.mt-2.text-sm.text-gray-500
            = @book.title
        div
          label.block.text-sm.font-medium.text-gray-700
            | Average Rating
          p.mt-2.text-sm.text-gray-500
            = @book.average_rating.to_f.round(1)
        div
          label.block.text-sm.font-medium.text-gray-700
            | Rating Count
          p.mt-2.text-sm.text-gray-500
            = @book.rating_count
        div
          label.block.text-sm.font-medium.text-gray-700
            | Description
          p.mt-2.text-sm.text-gray-500
            == @book.description
        div
          label.block.text-sm.font-medium.text-gray-700
            | Loc Class
          p.mt-2.text-sm.text-gray-500
            = @book.loc_class
        div
          label.block.text-sm.font-medium.text-gray-700
            | Language
          p.mt-2.text-sm.text-gray-500
            = @book.language
        div
          label.block.text-sm.font-medium.text-gray-700
            | Pages
          p.mt-2.text-sm.text-gray-500
            = @book.pages
        div
          label.block.text-sm.font-medium.text-gray-700
            | Isbn13
          p.mt-2.text-sm.text-gray-500
            = @book.isbn13
        div
          label.block.text-sm.font-medium.text-gray-700
            | Release Date
          p.mt-2.text-sm.text-gray-500
            = @book.release_date
        div
          label.block.text-sm.font-medium.text-gray-700
            | Summary
          p.mt-2.text-sm.text-gray-500
            == @book.summary
        div
          label.block.text-sm.font-medium.text-gray-700
            | Content Cleaned
          p.mt-2.text-sm.text-gray-500
            = @book.content_cleaned
        div
          label.block.text-sm.font-medium.text-gray-700
            | Content Available
          p.mt-2.text-sm.text-gray-500
            = @book.content_available
      .bg-gray-50.px-4.py-3.text-right.sm:px-6
        = link_to 'Edit this book', edit_book_path(@book), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"
        .inline-block.ml-2
          = button_to 'Destroy this book', book_path(@book),form: { data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } }, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium"
        = link_to 'Back to books', books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium"